---
- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: present
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat={{ filebeat_version }}
    state: present
  notify:
    - restart filebeat
