---
- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"
    state: present

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: "{{ filebeat_state }}"
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat={{ filebeat_version }}
    state: "{{ filebeat_state }}"
    cache_valid_time: "{{ filebeat_cache_valid_time }}"
  notify:
    - restart filebeat
