---
- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"
    state: "{{ filebeat_state }}"

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: "{{ filebeat_state }}"
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat={{ filebeat_version }}
    state: "{{ filebeat_state }}"
  notify:
    - restart filebeat
