---
- set_fact:
    filebeat_apt_repo: "{{ filebeat_apt_repo_v1 }}"
  when: filebeat_version < '5.0.0'

- set_fact:
    filebeat_apt_repo: "{{ filebeat_apt_repo_v5 }}"
  when: filebeat_version >= '5.0.0'

- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: present
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat={{ filebeat_version }}
    state: "{{ filebeat_package_state }}"
  notify:
    - restart filebeat
