---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: copy ca certificate if required
  copy:
    src: "{{ filebeat_ca_local_path }}"
    dest: "{{ filebeat_ca_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ca_local_path|default(None) != None

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true
